version: '3'

services:
  db:
    image: postgres
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=marat
      - POSTGRES_PASSWORD=marat123
      - POSTGRES_DB=marat
    restart: always
  service:
    build: .
    ports:
      - 8072:8072
    depends_on:
      - db
      - nats-streaming-server
    restart: always
  nats-streaming-server:
    image: nats-streaming:latest
    ports:
      - 4222:4222
      - 8222:8222
    restart: always

volumes:
  postgres-data:
